---
- name: copy files from one managed node to other
  hosts: 172.31.5.97
  tasks:
   - name: Fetch a file from server1 to controller
     fetch:
      src: file300
      dest: /tmp
- name: copy the file fetched from server1 into server2
  hosts: 172.31.12.236
  tasks:  
   - name: copy the file to server2
     copy:
      src: //tmp/172.31.5.97/file300
      dest: /home/ubuntu 

...
      
